
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luz Robles
 */
public class NewJFrame extends javax.swing.JFrame {
private Lienzo objeto=new Lienzo(this);
Mascota pun=new Mascota();
Hilo h=new Hilo(this);
boolean activaCom=false;
boolean activaSho=false;
boolean activaPel=false;
int contadorTimer = 0;
int contadorSho = 0;
int contadorPel = 0;
Timer t = new Timer(1000,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae) {
            contadorTimer++;
            //JOptionPane.showMessageDialog(null,contadorTimer);
            if(contadorTimer==4){
            contadorTimer=0;
            activaCom=false;
            objeto.repaint();
            
            t.stop();
            }
            //objeto.repaint();
        }        
    });
Timer tSho = new Timer(1000,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae) {
            contadorSho++;
            //JOptionPane.showMessageDialog(null,contadorTimer);
            if(contadorSho==4){
            contadorSho=0;
            activaSho=false;
            objeto.repaint();
            
            tSho.stop();
            }
            //objeto.repaint();
        }        
    });
Timer tPel = new Timer(1000,new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae) {
            contadorPel++;
            //JOptionPane.showMessageDialog(null,contadorTimer);
            if(contadorPel==4){
            contadorPel=0;
            activaPel=false;
            objeto.repaint();
            
            tPel.stop();
            }
            //objeto.repaint();
        }        
    });


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        objeto.setSize(800,600);
        this.setLocation(0,0);
        this.add(objeto);
        this.setLocationRelativeTo(this);
        
        //t.start();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComida = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comida1.png"))); // NOI18N
        btnComida.setText("jButton1");
        btnComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComidaActionPerformed(evt);
            }
        });

        btnLimpia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/showe1.png"))); // NOI18N
        btnLimpia.setText("jButton1");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yarn.png"))); // NOI18N
        btnJugar.setText("jButton1");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnComida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btnLimpia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComidaActionPerformed
        //h.start();
        activaCom=true;
        objeto.repaint();
        objeto.comida=200;
        t.start();
        
    }//GEN-LAST:event_btnComidaActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        activaPel=true;
        objeto.repaint();
        objeto.jugar=200;
        tPel.start();
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        activaSho=true;
        objeto.repaint();
        objeto.shower=200;
        tSho.start();
    }//GEN-LAST:event_btnLimpiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComida;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnLimpia;
    // End of variables declaration//GEN-END:variables
}
